### ISSUE TITLE
small_3D_lima runs x10 longer since MesoNH 5.6->5.7 contribution

### ISSUE THREAD

**Issue by QuentinRodier** [UMR-CNRM/PHYEX#49]
I forgot to send a PR for the contrib...
Does it come from the ELEC contrib or already before ?
Check the branch check_mesonh_dev_0.6.3_to_master

branch master : commit 7f5af68 : runtime OK
branch check_mesonh_dev_0.6.3_to_master, commit 5b8e8cec (before ELEC) : runtime OK

**Comment by SebastienRietteMTO** [comment]
Time is spent in aro_adjust_lima

**Comment by SebastienRietteMTO** [comment]
Fixed by e02f881925ac874bfdb23f461d8dfa0db82d8e52
